name: Build & Scan Docker Image

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_NAMESPACE: sparetimecoders
    steps:
      - uses: actions/checkout@v1

      - name: Dockerfile lint
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: buildtool/actions/build@master
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Scan with Phonito Security
        uses: phonito/phonito-scanner-action@master
        with:
          image: sparetimecoders/rabbitmq:${{ GITHUB_SHA }}
          phonito-token: ${{ secrets.PHONITO_TOKEN }}

      - name: Push the Docker image
        uses: buildtool/actions/push@master
